version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 21.6 # Specify the Node.js version
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Running tests...
      - npm test

  build:
    commands:
      - echo Building the application...
      - npm run build || echo 'No build script, continuing...'

  post_build:
    commands:
      - echo Application build complete.

artifacts:
  files:
    - public/**
    - server.js
    - package.json
    - package-lock.json
